### ISSUE TITLE
file is encrypted or is not a database

### ISSUE THREAD

**Issue by avary** [ppwwyyxx/wechat-dump#12]
hello,
im trying to use this tool on ubuntu 14.04.2 LTS
when i run decrypt-db.sh, i got followng errors
error near line3 : files is not encrypted or is not a database
error near line4 : files is not encrypted or is not a database
error near line5 : no such database:db

i double checked imei & uin.. they are correct.
any idea how to fix this ?

**Comment by ppwwyyxx** [comment]
Error like this happens when the decryption key is not correct. Or it's also possible that your database file is broken.
I gave several ways of getting imei & uin in README.md. And I'm not sure they behave the same on different phones. You may try seeing into that.

**Comment by avary** [comment]
hi, it seems that my database was broken, after i migrated my chat log to another device(runs 4.4.2 BTW) i got it decrypted.
thanks alot.

**Comment by ppwwyyxx** [comment]
Hi, it will be great if you could leave your device information, for the cases it works and not, in [the wiki page](https://github.com/ppwwyyxx/wechat-dump/wiki).
