### ISSUE TITLE
`db-decrypt` should be `db_decrypt` in README.md

### ISSUE THREAD

**Issue by FallenMax** [ppwwyyxx/wechat-dump#13]
`./android-interact.sh db-decrypt` should be `./android-interact.sh db_decrypt` in `README.md` ( `-` vs `_`)

Also, `./android-interact.sh imei` failed silently (console printed: `Getting imei... Getting db...`). I circumvented by hardcoding IMEI into .sh :P  
Anyway, this project looks like the only working solution to export Wechat chatlog for Android, thanks for your work!

**Comment by ppwwyyxx** [comment]
Cool. I fixed the name. 
And the script now writes error message to stderr. won't be silent.
For IMEI, I really don't know the best way to fetch it. I know my method fails on some phones.
