### ISSUE TITLE
[Feature Request] Add iOS support

### ISSUE THREAD

**Issue by nebulakl** [ppwwyyxx/wechat-dump#18]
It would be great if your program can dump wechat messages from iOS backup as well.

Reference: http://candleforlove.com/forums/topic/46146-how-to-download-wechat-logs-from-an-iphone/

**Comment by SilverBut** [comment]
Recently I just found that though dump the message is not easy, you can use some third-party tools such as `iMazing` to get a full backup of a application, which is a zip file for `iMazing`. If you can get it for Wechat, you can just unzip the backup file, and see unencrypted chat logs, which can be processed by this tool.
