### ISSUE TITLE
Group Chats are missing usernames

### ISSUE THREAD

**Issue by cointracker** [ppwwyyxx/wechat-dump#19]
Group chats seem to dump ok except the messages have the name of the chat group instead of the usernames of the person sending the message.

**Comment by ppwwyyxx** [comment]
Group chat name is a problem indeed. I haven't had the time to look into that.

**Comment by ppwwyyxx** [comment]
I pushed a patch just now to handle group chat username properly when using dump-msg.py.
 Seems to work with my data.
