### ISSUE TITLE
pysqlcipher.dbapi2.DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by dequn** [ppwwyyxx/wechat-dump#21]
Hello, I try ./decrypt-db.py by manual, the title is what I get ,while my env is 

wechat version:6.3.13
mobile:H30-U10
OS: OS X
pysqlcipher version:2.6.4

My imei and wxuid is Ok.

**Comment by ppwwyyxx** [comment]
I'm not sure what's the problem. You may have a try on the old decryption tools (which uses a different way to decrypt):
```
cd legacy
ln -sv ../compatibility.sh ./
./decrypt-db.sh <path to EnMicroMsg.db> <imei> <uin>
```

**Comment by dequn** [comment]
It seems like the KEY is error , I got the key and open EnMicroMsg.db in Navicat ,it also give the same error tip.While I'm sure the IMEI and WXUID is ok. Thanks.

**Comment by simbaforrest** [comment]
It seems that Wechat changed the KEY? I got exactly the same error...... Anyone recently tried with success?

**Comment by dequn** [comment]
Yes, I also think so.

**Comment by simbaforrest** [comment]
Wow, so it means this is not working anymore? What can we do now? V_V @dequn

**Comment by dequn** [comment]
Well, I don't know so far, how did they know the encrypting method , can we hack it ?  @simbaforrest

**Comment by simbaforrest** [comment]
I have no idea how they found out the KEY...... @dequn

**Comment by ppwwyyxx** [comment]
The decryption still works today as I tested on my latest version of wechat. So it's unlikely that they changed the method.
It could be possible that encryption (how the key is generated, how the sqlcipher library is used)  is different in different phones, and unfortunately I couldn't guess what's the problem.

**Comment by simbaforrest** [comment]
What phone do you use? Mine is a Nexus 6...... @ppwwyyxx

**Comment by ppwwyyxx** [comment]
I use XiaoMi Mi3W.  There is a [wiki page](https://github.com/ppwwyyxx/wechat-dump/wiki) contributed by some users about what works and what doesn't.

**Comment by simbaforrest** [comment]
This sounds weird... I cannot think of a reason why they want to write codes that uses different encryption for different phones... Maybe something else was wrong...

**Comment by ppwwyyxx** [comment]
I agree with you, this is weird. But still, I can do nothing unless I have the phone or some data to look at.
Are you a fairly new wechat user or an old user? It could be possible that they use some new mechanism for new users but keep things for old users for compatibility.

**Comment by simbaforrest** [comment]
I totally understand, sorry for too many posts here...
I start using Wechat three or four years ago so I guess I am "old" enough, lol

**Comment by chg-hou** [comment]
I also suffered the same issue on Meizu MX4: correct imei and uid, but wrong password.
I wrote a tool to crack the passwrod.
[https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker](https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker)
Although it takes days, at least we won't be blocked from our own messages.
@simbaforrest @dequn

**Comment by ppwwyyxx** [comment]
@chg-hou That's a great tool! Thanks!

**Comment by marekyggdrasil** [comment]
WeChat 6.5.4,
Xiaomi MI4LTE,
Same issue here, however I attempted it on backups extracted using Windows WeChat client backup tool.

**Comment by imWildCat** [comment]
After the open-source of WCDB (https://github.com/Tencent/wcdb), can this library work?
`.db` could not be sqlite anymore

I have same issue which cannot decrypt.

```shell
➜  wd git:(master) ✗ ./decrypt-db.py EnMicroMsg.db [hidden] [hidden]
decrypted.db already exists. Remove? (y/n) y
KEY: [hidden]
Decrypt and dump database to decrypted.db ...
Traceback (most recent call last):
  File "./decrypt-db.py", line 53, in <module>
    c.execute("ATTACH DATABASE '" + args.output + "' AS db KEY '';")
pysqlcipher.dbapi2.DatabaseError: file is encrypted or is not a database
```

**Comment by prusswan** [comment]
One potential pitfall: make sure the EnMicroMsg.db is dumped correctly. My phone is not rooted (but has su installed), so I need to copy the db file somewhere, fix the permissions, before trying to cat/pull it: 		

    adb shell "su -c 'cp $MM_DIR/MicroMsg/$chooseUser/EnMicroMsg.db /data/local/tmp && chown shell.shell /data/local/tmp/EnMicroMsg.db'; cat /data/local/tmp/EnMicroMsg.db" > EnMicroMsg.db

If the file is not dumped correctly, there is no way to tell from the errors (it can never be decrypted).

**Comment by zhang-ray** [comment]
same as me.
I'm using WeChat 7.0.x.

**Comment by ppwwyyxx** [comment]
I rewrote the decryption logic by improving pysqlcipher usage and adding more ways to obtain IMEI and UIN. It may increase the chance of success.

However, things might be different on everyone's phone and it's hard to help with other people's phones. More generally, other ways to increase chance of success are listed in https://github.com/ppwwyyxx/wechat-dump/issues/64 and any help to implement them would be appreciated.
