### ISSUE TITLE
请问Android下能获取群聊群成员的群昵称吗？

### ISSUE THREAD

**Issue by truistic** [ppwwyyxx/wechat-dump#22]
你好，请问Android下能获取群聊群成员的群昵称吗？

**Comment by ppwwyyxx** [comment]
数据可以拿到…但是我并没有实现这部分
2016年3月8日 上午8:58，"truistic" <notifications@github.com>写道：

**Comment by truistic** [comment]
是在friend_ext表里吗？我解密出来的EnMicroMsg.db里面这个表为空。。

**Comment by ppwwyyxx** [comment]
我记得好像跟其他普通联系人是在同一个表里.

**Comment by ppwwyyxx** [comment]
Should be fixed in 77191e1885d.
