### ISSUE TITLE
I can not find EnMicroMsg.db in Wechat 6.2.2

### ISSUE THREAD

**Issue by standin000** [ppwwyyxx/wechat-dump#26]
Is it because tencent updating ,or I use wrong method?

**Comment by ppwwyyxx** [comment]
If you root your device, the file should be at
```
/data/data/com.tencent.mm/MicroMsg//verylongusername/
```
6.2.2 should work fine. Not sure what's the problem on your side.

**Comment by standin000** [comment]
Thanks very much, I only find /mnt/sdcard/tencent/MicroMsg/verylongusername/ directory, now I found it.
