### ISSUE TITLE
Improvements for README.md

### ISSUE THREAD

**Issue by h82k** [ppwwyyxx/wechat-dump#29]
By following the steps I've found some difficulties if one is not professional (like me).
1. the module requests wasn't found for me, so I'd suggest to add that in the dependencies section (installation with: pip install requests)
2. "download uncompress emoji.cache" is not accurate enough, for me it wasn't clear that you'll have to uncompress first in wechat-dump folder and the uncompress the output again with emoji-cache-tool.py
   For me it seemed to work with this command: ./emoji-cache-tool.py unpack ./resource/emoji/
3. ./dump-html.py decrypted.db avatar.index resource "<contact_name>" output.html
   A further example would be nice, "<contact_name>" is the display name, I'd recommend to enter anything and then there are displayed all contact_name(s) in right format.
4. Entering this command with correct username gave out an error, the parameters would be wrong, I suggest leaving them out or write the command as stated in dump-html.py:
   ./dump-html.py --db decrypted.db --avt avatar.index --res resource "<contact_name>" --output output.html

Thank you really much for this awesome tool, it's amazing how much effort you've put in there and how nice the result looks!

Sincerely Malte

EDIT: Btw it's working for me with LG Optimus 4X HD Android 4.4.4 Omni Rom, I'm not able to write that in the wiki

**Comment by weakish** [comment]
> it's working for me with LG Optimus 4X HD Android 4.4.4 Omni Rom,
> I'm not able to write that in the wiki

Added the phone/os to wiki.

**Comment by ppwwyyxx** [comment]
Thanks a lot for your suggestions!
One thing about the PR: unpacking emoji should not be necessary. I think things should work without running `emoji-cache-tool.py`. That tool is mainly for me to see what's in the cache.
