### ISSUE TITLE
android 5.0 and 6.0 can't get imei num

### ISSUE THREAD

**Issue by loveofyou** [ppwwyyxx/wechat-dump#33]
Hi:
    when i try use this object export my wechat_history find some issues.

  My Device : Moto X Style , Android 6.0.1 , Rooted . double Sim
 1 The Script can't get the right Imei ,must be defind  devices imei . (Because my devices have two imei)
 2 And can't  use "eu.chainfire.adbd" open "adb root" ,  could we don't use root to get EnMicroMsg.db , tech user use example code manual copy this file to sdcard or other space .
`adb shell`
`su`
`cp -fR /data/data/com.tencent.mm/ /sdcard/somewhere`

thanks

**Comment by ppwwyyxx** [comment]
Sorry I don't know how to get the right IMEI if there are two.
And I don't know why `adb root` won't work for you. I don't have such phones for testing.

**Comment by loveofyou** [comment]
thank you  for anwser .

i think we can use this code to  get two imei ,then try these imei to decode EnMicroMsg.db  .
`adb shell service call iphonesubinfo 1`
`adb shell service call iphonesubinfo 3`

**Comment by ppwwyyxx** [comment]
On my phone when I call `*#06#` there are 3 IMEI. One of them works. And it's not shown up in `adb shell service call`.
So I don't know any proper solution and users are expected to try this by themselves.

**Comment by YibaiMeng** [comment]
@ppwwyyxx same for my phone! I have a Redmi 5A and the working IMEI is neither of the two IMEIs of the networking interfaces.  It's called MEID and it shows up when I call *#06#, but I can't find it anywhere else.

**Comment by prusswan** [comment]
The issue with multiple IMEIs might be fixable by checking CompatibleInfo.cfg (as per the suggestion in #42   to run `strings CompatibleInfo.cfg`, the IMEI is in one of the strings)

**Comment by oakieville** [comment]
i know im late but just to point out all devices with imei have an meid. Imei is 15 digits meid is 14 the 15th digit of imei is a lunh checksum calculated by the first 14 digits, them meid is the same as the imei but without the 15th digit (the luhn checksum)
