### ISSUE TITLE
Unable to install pysox/libsox-dev on Mac OS El Capitan

### ISSUE THREAD

**Issue by whhsw** [ppwwyyxx/wechat-dump#35]
Hi, thanks for this awesome project at first!

I got question for the setup. I could successfully run the project in Ubuntu.
However, in mac os, when trying to pip install pysox, received below error.

   pysox/sox.c:227:10: fatal error: 'sox.h' file not found
    #include "sox.h"
             ^
    1 error generated.

This seems to be a problem related to lack of libsox-dev in Mac. I searched all across google and stackoverflow, but have not figured out a way to do it. 

Would you help on this? Thanks!

**Comment by ppwwyyxx** [comment]
https://github.com/rabitt/pysox seems to have a solution for you.

**Comment by whhsw** [comment]
though named pysox, that lib has a very different api compared to the pysox lib you used in the repo. But anyway, I just realized that sox is for wechat version < 6.0, so I can just comment that part of code out...
