### ISSUE TITLE
I am not able to find out avatar.index file

### ISSUE THREAD

**Issue by blueyestar** [ppwwyyxx/wechat-dump#45]
Hi @ppwwyyxx ,
    There is no avatar.index file under /data/data/com.tencent.mm/MicroMsg/${userid}/sfs/

    Do you have an idea?

    WeChat version: 6.5.8
    Android: 7.1.1
    phone: Oneplus 3
    
Thanks

**Comment by liukangxu** [comment]
I encountered the same problem.

WeChat version: 6.5.8
Android: 6.0.1 (MIUI 8.5.2.0)
Phone: Mi 5s

**Comment by ppwwyyxx** [comment]
The format probably has changed. I'll take a look when I have time.

**Comment by darkskygit** [comment]
it look like save to /sdcard/tencent/MicroMsg/{userid}/avatar?
i find same friend avatar in this folder.

**Comment by ppwwyyxx** [comment]
Should be fixed by #50.
