### ISSUE TITLE
Analyze and backup database on Mac?

### ISSUE THREAD

**Issue by LinxiFan** [ppwwyyxx/wechat-dump#46]
I recently deleted my chat log with parents on the phone by accident. Fortunately, the log has been synced to the Mac wechat portal. I wonder whether I can use a variant of your script to backup the chat log? 
If not, is there any other work on analyzing wechat Mac database? Thanks!

**Comment by ppwwyyxx** [comment]
Unfortunately I don't know any way to help with this.
