### ISSUE TITLE
How to dump HTML by username rather than nickname? OR How to input special username into dump HTML?

### ISSUE THREAD

**Issue by ajburley** [ppwwyyxx/wechat-dump#51]
**My situation**: I am using Ubuntu Server 17.10. Presumably due to the terminal capabilities, I am not able to view the special characters in nicknames in the output of "list-chats.py". They just come up in the terminal as a diamond followed by a space. So it's seemingly impossible for me to pass this nickname to "dump-html.py".

**Issue**: I don't understand why "dump-html.py" accepts only the nickname and not the username, which is also written out by "list-chats.py". Is it possible for "dump-html.py" to accept the username, e.g. "wxid_45vu0n3vt"?

If not, is it possible for "list-chats.py" to be able to write out the "nickname" using some pure ASCII via some encoding, which could then be decoded inside "dump-html.py"?

**Note**: Sorry I am not very familiar with Python. I am proficient with Java. Also, I know very little about UNIX character encoding behaviours.

**Comment by ajburley** [comment]
I modified dump-html.py to remove the try block and instead accept `chatid` directly from args. Not sure if this will actually work. I am getting another issue, will raise another issue.

**Comment by ppwwyyxx** [comment]
both id and nickname are supported now
