### ISSUE TITLE
Is HTML the only form of exported data?

### ISSUE THREAD

**Issue by cs-usst** [ppwwyyxx/wechat-dump#53]
I can't use wechat dump for some reason. (my IMEI is randomized and i have to crack the key)
So before dumping chat history, I need to know something about the exported data, I need to make my chat history as index-able as the built-in wechat.
Is it possible? For long history, is the HTML file very long?

**Comment by rom1504** [comment]
The SQLite database contains all the information, you can query it as you
like.

**Comment by cs-usst** [comment]
But I can't see photos and videos directly within the sqlite database, right?
So it's not as easy as the search feature in wechat app.
In the app I can see rendered chat history, including photos and videos. And I can just check the photos and jump to its context.

**Comment by rom1504** [comment]
Well obviously, if you want a fully featured chat viewer you need to
implement it.
One way to do that is using the sql database.
If you just want to use something, the HTML generated by wechat-dump is
already pretty neat but yes not fully featured.
