### ISSUE TITLE
How is WeChat 6.5.* encryption mechanism different from the previous version?

### ISSUE THREAD

**Issue by cs-usst** [ppwwyyxx/wechat-dump#54]
Here's what I've tried to decrypt my wechat database. They are all failed:

1. Regular method: Tried to read the IMEI no. of my phone and combine it with wechat uin, then use the md5 hashed password to decrypt the database.
2. Transfer my chat history to another phone and tried to decrypt with its IMEI and uin.
3. Back up my chat history to my PC and restore on another phone. Then decrypt.
4. Decrypt with [password cracker](https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker). I tried all possibilities.

I read from other [post](https://blog.slinuxer.com/2015/10/%E5%BE%AE%E4%BF%A1%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95) that since WeChat 6.5.*, the encryption mechanism is changed.
Is that the reason that I failed?

And btw, some of my chat history has reached almost 60000 lines. Is it possible to export?

**Comment by rom1504** [comment]
I have version 6.6.2 and can still decrypt without any problem.
What's the difference with your case ?
Did you create a new account after 6.5 release ?

**Comment by cs-usst** [comment]
I created my account long time ago.
And the only difference is that i used a Xposed module to randomize my IMEI. That's why I tried method 2,3 and 4 above.

By the way, in #42 @ChiChou provided a gist, which I don't know how to use. The gist is claimed to be able to get the actual device id.

**Comment by ChiChou** [comment]
https://github.com/ppwwyyxx/wechat-dump/issues/42#issuecomment-367905450

**Comment by ppwwyyxx** [comment]
Now the method provided by @ChiChou was implemented in our decryption script
