### ISSUE TITLE
decrypt wechat desktop backups

### ISSUE THREAD

**Issue by goldfish500** [ppwwyyxx/wechat-dump#55]
Can someone check if this program work for wechat desktop backups? Since you can backup chats on desktop to couple files: BAK_0_MEDIA  BAK_0_TEXT  Backup.db, can this program decrypt those file? In this way you do not need to root your phone (suppose I know my IMEI and UID).

**Comment by smasterfree** [comment]
the nearest solution is http://bbs.iosre.com/t/macos-dump-wechat/8207 

but the author do not really decrypt the db.
