### ISSUE TITLE
[@res.py:wechat.res] Cannot get emoji [md5] in None

### ISSUE THREAD

**Issue by vflanker** [ppwwyyxx/wechat-dump#59]
I cound found the file named by [md5] in directory Resource/emoji/, but it keep warn me that "Cannot get emoji [md5] in None'. I compared the chat history by chat time and found that those which counld not be found in None were all emoji that added by user themselves, and those official emoji or most downloaded emoji's album from wechat official shop can be showed as normal. I cound not figure it out why there is certain file under the right directory but it kept saying nothing found.
![image](https://user-images.githubusercontent.com/30745146/46838519-3c278900-cdec-11e8-8718-418722783b40.png)
(ps: I add some code and with these output below, it seems that problem occured in function query)

**Comment by ppwwyyxx** [comment]
Although the file exists in `resource/emoji`, it is an encrypted image file and I have not figured out the decryption. This was added to [todo-list](https://github.com/ppwwyyxx/wechat-dump#todo-list) and any help is welcome.
