### ISSUE TITLE
Can't find the avatar.index, Version 6.6.5

### ISSUE THREAD

**Issue by olrearn** [ppwwyyxx/wechat-dump#61]
I can't find the document named avatar.index.
Does that matter?
Can anyone help me?Thanks!

**Comment by zhang-ray** [comment]
same as me.
I'm using WeChat 7.0.x. I got the message like below:
```
sfs/avatar.index' does not exist
```

**Comment by ppwwyyxx** [comment]
In latest wechat, this file is not needed anymore and avatar can be decoded without this file.
