### ISSUE TITLE
转发给自己的信息无法导出 

### ISSUE THREAD

**Issue by cangling** [ppwwyyxx/wechat-dump#63]
版本 6.6.2
wechat-dump-2018-0826

转发给自己的信息，导出 html 后 全部是下面这个链接，没有转发的信息。

URL:https://support.weixin.qq.com/cgi-bin/mmsupport-bin/readtemplate?t=page/favorite_record__w_unsupport&from=singlemessage&isappinstalled=0

**Comment by ppwwyyxx** [comment]
不清楚什么是"转发给自己的信息". 如果表述的更清楚，也许能得到社区的帮助
