### ISSUE TITLE
WeChat uses fixed string for IMEI on Android 10

### ISSUE THREAD

**Issue by wzyboy** [ppwwyyxx/wechat-dump#70]
According to [this comment](https://github.com/WANZIzZ/WeChatRecord/issues/7#issuecomment-695331151), WeChat uses the fixed string `1234567890ABCDEF` in place of IMEI on Android 10 devices. I've verified this and the first 7 chars of `md5('1234567890ABCDEF' + uin)` is actually the real password of my `EnMicroMsg.db`.

Maybe we should document this in README, or even try this as a fallback method in the automatic script.

**Comment by ppwwyyxx** [comment]
thanks! now added
