### ISSUE TITLE
 avatar.index File not found in sfs

### ISSUE THREAD

**Issue by jackkingc** [ppwwyyxx/wechat-dump#71]
wechat version ：7.0.16
phone ：mi8
android：9

I have cracked the password of the database with EnMicroMsg.db-Password-Cracker but I found no file in sfs including hidden files，and also video,voice2 in any wechat file，maybe WeChat changed the saving method？

**Comment by ppwwyyxx** [comment]
`avatar.index` only appears in old versions of wechat. Newer versions store avatars under `sfs/avatar`. The code should be able to find both versions of avatar (https://github.com/ppwwyyxx/wechat-dump/pull/50)

**Comment by jackkingc** [comment]
These files may be saved in different paths in different phones（avatar,emoji,image2,voice2,video）
phone :mi8 
wechat version ：7.0.16
android：9
I found these files under these paths,Hoping This Helps

avatar&image2:  /data/data/com.tencent.mm/MicroMsg/${userid}/
voice2&video&emoji:  /sdcard/Android/data/com.tencent.mm/${userid}/
