### ISSUE TITLE
imei not found in CompatibleInfo.cfg

### ISSUE THREAD

**Issue by ibaozi-cn** [ppwwyyxx/wechat-dump#73]
红米 10X
Android10

1.
"""Result: Parcel(
    0x00000000: ffffffff 00000058 00650067 00440074 '....X...g.e.t.D.'
    0x00000010: 00760065 00630069 00490065 003a0064 'e.v.i.c.e.I.d.:.'
    0x00000020: 00540020 00650068 00750020 00650073 ' .T.h.e. .u.s.e.'
    0x00000030: 00200072 00300031 00340032 00200030 'r. .1.0.2.4.0. .'
    0x00000040: 006f0064 00730065 006e0020 0074006f 'd.o.e.s. .n.o.t.'
    0x00000050: 006d0020 00650065 00200074 00680074 ' .m.e.e.t. .t.h.'
    0x00000060: 00200065 00650072 00750071 00720069 'e. .r.e.q.u.i.r.'
    0x00000070: 006d0065 006e0065 00730074 00740020 'e.m.e.n.t.s. .t.'
    0x00000080: 0020006f 00630061 00650063 00730073 'o. .a.c.c.e.s.s.'
    0x00000090: 00640020 00760065 00630069 00200065 ' .d.e.v.i.c.e. .'
    0x000000a0: 00640069 006e0065 00690074 00690066 'i.d.e.n.t.i.f.i.'
    0x000000b0: 00720065 002e0073 00000000 00000000 'e.r.s...........')"""

2.
Parcel(encode(info.strip())).get_utf16()

logger:
found imei=getDeviceId: The user 10240 does not meet the requirements to access device identifiers. from iphonesubinfo

then try
os.system(f"cat CompatibleInfo.cfg")

logger:
imei not found in CompatibleInfo.cfg

**Comment by ppwwyyxx** [comment]
The warnings are expected according to https://github.com/ppwwyyxx/wechat-dump/issues/70. It says the imei for Android 10 is a fixed string.
