### ISSUE TITLE
Python 3.9 support?

### ISSUE THREAD

**Issue by lockywolf** [ppwwyyxx/wechat-dump#78]
Pysqlcipher won't build with python 3.9. 

Line 182 of https://github.com/rigglemania/pysqlcipher3/blob/master/src/python3/row.c has several problems. <s> `tp_print` can be replaced with `tp_vectorcall_offset`,  but the code still won't build. </s>

This file is taken from pysqlite, which is py2-only, and pysqlite3 does not have a row_print function, so I didn't find an easy fix to make it compile with py3.9. 

Any hints?

I made a pull request just disabling this function, but I am not sure it is actually valid.

https://github.com/rigglemania/pysqlcipher3/pull/23

**Comment by ppwwyyxx** [comment]
It seems the upstream issue is already fixed.
