### ISSUE TITLE
Changes in directory structure? (i.e. no sfs/avatar.index)

### ISSUE THREAD

**Issue by lockywolf** [ppwwyyxx/wechat-dump#80]
Hello!

On my phone, OnePlus 5t, there is no avatar.index, neither in /data/data/com.tencent.mm/** , nor in /sdcard/Android/data/com.tencent.mm/** (checked with find . -iname '*avatar.index*')
There isn't even a directory called 'sfs'.

There are, however, two folders called "avatar", in `/data/data/com.tencent.mm/MicroMsg/${long_id}`, and in `/sdcard/Android/data/com.tencent.mm/MicroMsg/${long_id2}`, as well as two folders called `image2`.

Note that ids also differ.

Is this a well-known change? Shall the code be adjusted somehow?
(Or, maybe, a wiki page created, describing the existing wechat folder structure?)

**Comment by ppwwyyxx** [comment]
> There isn't even a directory called 'sfs'.

It is expected. It only exists in old version of wechat.

> There are, however, two folders called "avatar"

It's hard to tell which one is actually used
