### ISSUE TITLE
adb shell dumpsys iphonesubinfo not working since Android 5.0 Lollipop

### ISSUE THREAD

**Issue by chaserhkj** [ppwwyyxx/wechat-dump#9]
As it is indicated in the title, `adb shell dumpsys iphonesubinfo` is not working since Android 5.0 Lollipop, causing `./android_interact.sh imei` to fail with these devices

[This](http://stackoverflow.com/questions/27002663/adb-shell-dumpsys-iphonesubinfo-not-working-since-android-5-0-lollipop) page on stackoverflow pointed out the correct way of getting imei on Lollipop devices, please consider supporting this, as Lollipop devices are getting more and more around us.

**Comment by ppwwyyxx** [comment]
I don't have a android 5.0 device for testing. Pull requests are welcomed.
