### ISSUE TITLE
decrypt-db.py:wechat] An unexpected error occurred.invalid literal for int() with base 10: '0 community'

### ISSUE THREAD

**Issue by fashioncj** [ppwwyyxx/wechat-dump#90]
不兼容版本字符串
version_str = 4.5.0 community

```
version = tuple([int(x) for x in version_str.split(".")])
```

建议修改为:
`version_str.split(" ")[0].split(".")`

**Comment by delicacyyy** [comment]
我直接注释掉了

**Comment by m34nbunny** [comment]
version_str = list(conn.execute("PRAGMA cipher_version"))[0][0].replace(" community", "")
